FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app

RUN adduser -u 5679 --disabled-password --gecos "" amorphie-tokenuser && chown -R amorphie-tokenuser:amorphie-tokenuser /app
USER amorphie-tokenuser

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["./amorphie.token/amorphie.token.csproj", "."]
RUN dotnet restore "./amorphie.token.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "./amorphie.token.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "./amorphie.token.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
EXPOSE 5000
ENV ASPNETCORE_URLS=http://+:5000
ENTRYPOINT ["dotnet", "amorphie.token.dll"]